Settings: Update Chinese translation
yaap/packages_apps_Settings pull request #13
Opened 2022-03-15 22:38 UTC by NinelieZ

2022-03-15 22:43 UTC, idoybh commented
Please fix indentations and remove non translateable strings

2022-03-17 06:59 UTC, NinelieZ commented
Sorry for my carelessness, I've fixed them, please check.

2022-03-20 07:16 UTC, idoybh requested changes

2022-03-20 07:16 UTC, idoybh commented on res/values-zh-rCN/yaap_configs.xml
> +    <string name="config_customDozePackage" translatable="false"></string>
```suggestion
```

2022-03-20 07:16 UTC, idoybh commented on res/values-zh-rCN/yaap_strings.xml
> +    <string name="update_activity" translatable="false">eu.chainfire.opendelta.MainActivity</string>
```suggestion
```

2022-03-20 07:46 UTC, idoybh approved these changes

2022-03-20 07:47 UTC, idoybh commented
Thank you :)

2022-03-20 07:47 UTC, merged